name: app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  awesome_dialog: ^3.2.1
  awesome_snackbar_content: ^0.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
